// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture

float3 sunScreenPos;

RWTexture2D<float4> result_buffer;
RWTexture2D<float4> screen_buffer;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: Implement psudocode from the lab

    result_buffer[id.xy] = screen_buffer[id.xy];
}
